level_order: true
barrier_types: true
npc:
  randomize: true
  include_foolish: false
item_pool:
  bags: true
  keys: true
  hills_key: false
  candles: true
  coins: true
  plants: true
  rocks: true
  upgrades: true
  life_ups: true
  bonus_scrolls: false
  bonus_rewards: true
  race_rewards: true
  jewels: false
  trading_sequence: 'included'
enemy_spawn: false