level_order: "faramore"
barrier_types: true
item_pool:
  npc: true
  bags: true
  keys: true
  hills_key: false
  candles: true
  coins: true
  plants: true
  rocks: true
  upgrades: true
  life_ups: true
  bonus_scrolls: true
  bonus_rewards: true
  race_rewards: true
  beacons: true
  jewels: false
  trading_sequence: "included"
logic:
  tricky_jumps: true
  no_lantern: true
  damage_boost: false